### ISSUE TITLE
Test and document SQL Script for preparing OMOP-formated data for loinc2hpo library

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/loinchpo#19]
- [x] Explain the script, step by step, so that users will be easily able to adapt the script to specific analysis goals.
- [x] Add the script to this repository

**Comment by iimpulse** [comment]
OMOP can be loaded in many formats on different platforms. OMOP2OBO supports loading from a csv file currently but we want to be able to support N3C as well.

- [ ] Create OMOP loader class for different required tables in different formats (dataframe or csv)
- [ ] Create OMOP Processor to process and impute loinc values based on current code in N3C
- [ ]  Acceptance requirements is to get the same table that we get at the end of n3c transform via loinchpo code.

**Comment by iimpulse** [comment]
depends on #28

**Comment by iimpulse** [comment]
Upon testing, data has been consistently been updated so an exact match is not possible. Will observe if first table is subset of second result set.

**Comment by iimpulse** [comment]
Data has been removed from N3C overall good coverage.
