### ISSUE TITLE
Logistic regression

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/loinchpo#23]
As a very simple example application of the library, let us
1. Do propensity matching to match non-COVID patients with COVID patients
2. Use logistic regression on all LOINC2HPO-related HPO terms to see which are significantly associated with COVID (roughly similar to the first LOINC2HPO paper)
3. Create a table with p-values for each regression coefficient

**Comment by iimpulse** [comment]
We would like this to be a separate paper in the future and will hold out on the jamia open paper for loinchpo
